// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftTK1doZWj_ZhQ3COB5UYySBrOber6U4',
    appId: '1:241295335602:web:7ef2617b6215f6832669ab',
    messagingSenderId: '241295335602',
    projectId: 'gfbf-5356d',
    authDomain: 'gfbf-5356d.firebaseapp.com',
    storageBucket: 'gfbf-5356d.appspot.com',
    measurementId: 'G-SP1HY8P65F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApvFyGCAjl6F4QrF2DaoZUiwC17WyYB4',
    appId: '1:241295335602:android:a62af8dc3474e4552669ab',
    messagingSenderId: '241295335602',
    projectId: 'gfbf-5356d',
    storageBucket: 'gfbf-5356d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3bXRkYWtpKzW7QXUPrm0YTrxVhv9yrA',
    appId: '1:241295335602:ios:806d973e08360f092669ab',
    messagingSenderId: '241295335602',
    projectId: 'gfbf-5356d',
    storageBucket: 'gfbf-5356d.appspot.com',
    iosBundleId: 'com.example.gfbf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3bXRkYWtpKzW7QXUPrm0YTrxVhv9yrA',
    appId: '1:241295335602:ios:806d973e08360f092669ab',
    messagingSenderId: '241295335602',
    projectId: 'gfbf-5356d',
    storageBucket: 'gfbf-5356d.appspot.com',
    iosBundleId: 'com.example.gfbf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDftTK1doZWj_ZhQ3COB5UYySBrOber6U4',
    appId: '1:241295335602:web:88bd5ad49148b2f52669ab',
    messagingSenderId: '241295335602',
    projectId: 'gfbf-5356d',
    authDomain: 'gfbf-5356d.firebaseapp.com',
    storageBucket: 'gfbf-5356d.appspot.com',
    measurementId: 'G-M3G4799QKW',
  );
}
